[package]
name = "earnings-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.16.0"
anyhow = "1.0.70"
chrono = "0.4.24"
tokio = { version = "1.27.0", features = ["full"] }
thirtyfour = "0.31.0"
async-trait = "0.1.68"
