[package]
name = "earnings-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.16", features = ["blocking"] }
scraper = "0.16.0"
anyhow = "1.0.70"
chrono = "0.4.24"
headless_chrome = "1.0.5"